/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [61.02KB] > /Users/morning/Desktop/talking-gpt/public/scene-transformed.glb [2.51MB] (-4014%)
Author: Jimmy Gunawan (https://sketchfab.com/jimmygunawan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blender-sushi-virtual-journal-16th-april-2020-634af2ae983f4fb8a9295e6b1b3d5c74
Title: Blender Sushi Virtual Journal, 16th April 2020
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="grp_eyeLeft_1" position={[-0.027, 0.031, 0.025]} rotation={[0.09, 0.004, 0.04]} scale={0.01}>
            <group name="eyeLeft_0">
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.lambert5} />
            </group>
          </group>
          <group name="grp_eyeRight_3" position={[0.038, 0.018, 0.024]} rotation={[0.09, -0.002, -0.024]} scale={0.01}>
            <group name="eyeRight_2">
              <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.lambert5} />
            </group>
          </group>
          <group name="grp_transform_6" rotation={[0.028, -0.202, -0.02]} scale={0.01}>
            {/* <group name="head_4">
              <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials.lambert5} />
            </group> */}
            <group name="teeth_5">
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.lambert5} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
